name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libtinfo6

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug