name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mostrar estructura COMPLETA
        run: |
          echo "📂 ROOT:"
          pwd
          ls -la

          echo "🔍 BUSCANDO buildozer.spec EN TODO:"
          find / -name buildozer.spec 2>/dev/null | head -n 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libffi-dev libssl-dev

      - name: Instalar Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK desde raíz
        run: |
          echo "📂 Donde estoy antes de build:"
          pwd
          ls -la

          buildozer android clean
          buildozer android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk